### ISSUE TITLE
Error on Cloud Usage Tab

### ISSUE THREAD

**Issue by lukebeamish-peak** [cloud-carbon-footprint/ccf-backstage-plugin#7]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
macOS 11.6.5
- **Browser:**
Chrome

### Expected Behaviour

Opening the Cloud Usage tab either shows the error a useful message that no data is available for the given period, or shows a graph of the emissions over the given period.

### Actual Behaviour

When navigating to the plugin in our Backstage instance, the page initially loads showing that no data is available for the period, and then immediately refreshes before displaying the error below underneath the plugin nav bars. The data range control is still shown and accessible and it is possible to reduce the date range when running locally. Similarly, when running locally via yarn-start and yarn start-backend, it is possible to navigate to other tabs which appear to be working correctly.

Note that this Backstage instance/plugin has been configured to pull data from AWS only.

**Full error message:**
```
VM40291 react_devtools_backend.js:4026 ErrorBoundary, error: TypeError: Cannot read properties of undefined (reading 'map'), info: [object Object]
    at ErrorBoundary2 (eval at ES6ProxyComponentFactory (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at div
    at Paper (webpack-internal:///../../node_modules/@material-ui/core/esm/Paper/Paper.js:47:23)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at Card (webpack-internal:///../../node_modules/@material-ui/core/esm/Card/Card.js:27:23)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at TabbedCard (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:6498:5)
    at div
    at Grid (webpack-internal:///../../node_modules/@material-ui/core/esm/Grid/Grid.js:235:35)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at Grid (webpack-internal:///../../node_modules/@material-ui/core/esm/Grid/Grid.js:235:35)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at EmissionsTab (webpack-internal:///../../node_modules/@cloud-carbon-footprint/backstage-plugin-frontend/dist/esm/Plugin-74b9ce5b.esm.js:26:3)
    at article
    at Content (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4447:11)
    at RoutedTabs (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4541:11)
    at TabbedLayout (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4581:52)
    at PluginTabs (webpack-internal:///../../node_modules/@cloud-carbon-footprint/backstage-plugin-frontend/dist/esm/Plugin-74b9ce5b.esm.js:88:3)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at FlatRoutes (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2547:81)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:24)
    at article
    at Content (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4447:11)
    at div
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:24)
    at Page (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:5763:11)
    at Plugin (webpack-internal:///../../node_modules/@cloud-carbon-footprint/backstage-plugin-frontend/dist/esm/Plugin-74b9ce5b.esm.js:142:19)
    at RoutableExtensionWrapper (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:476:13)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:69:11)
    at PluginErrorBoundary (eval at ES6ProxyComponentFactory (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Suspense
    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:531:21)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at FlatRoutes (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2547:81)
    at div
    at SidebarPage (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:3329:82)
    at Root (webpack-internal:///./src/components/Root/Root.tsx:81:17)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at E (webpack-internal:///../../node_modules/react-router/index.js:38:820)
    at SignInPageWrapper (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2419:18)
    at x (webpack-internal:///../../node_modules/react-router/index.js:37:23)
    at w (webpack-internal:///../../node_modules/react-router-dom/index.js:42:23)
    at AppRouter (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2431:26)
    at RoutingProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:1948:3)
    at CssBaseline (webpack-internal:///../../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:66:31)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:24)
    at Provider (webpack-internal:///./src/App.tsx:112:20)
    at AppThemeProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2166:29)
    at AppContextProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2057:3)
    at ApiProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:76:11)
    at Provider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2338:25)
    at App

```
### To Reproduce
1. Create a new Backstage instance.
2. Add the plugin to the backstage instance
3. Setup billing report and AWS Athena as per the instructions here.
4. Add the following to the app-config file:
```
cloudCarbonFootprint:
  client:
    dateRangeType: months
    dateRangeValue: 1
    groupBy: week
  aws:
    useBillingData: true
    athenaDbName: ATHENA_DB_NAME
    athenaDbTable: ATHENA_TABLE_NAME
    athenaRegion: AWS_REGION
    athenaQueryResultLocation: ATHENA_QUERY_BUCKET
    billingAccountId: "AWS_ACCOUNT_ID"
    billingAccountName: AWS_ACCOUNT_NAME
    authMode: AWS
  gcp:
    useBillingData: false
  azure:
    useBillingData: false
```
6. Navigate to the plugin within the Backstage instance.

### Screenshots
![image](https://user-images.githubusercontent.com/75254340/168839001-c373a732-1543-42d3-a7b7-31ed7c791a02.png)

### Additional Information

© 2022 Thoughtworks, Inc.

**Comment by lukebeamish-peak** [comment]
From our own digging, it looks like the chart colors aren’t part of the theme palette at the point when `getChartColors()` is called in the following: `node_modules/@cloud-carbon-footprint/client/src/pages/EmissionsMetricsPage/EmissionsOverTimeCard/ApexLineChart/ApexLineChart.tsx > const colors = getChartColors(theme).`

The error is coming from within the `node_modules/@cloud-carbon-footprint/client/src/utils/themes/index.ts` file when the function is attempting to map over theme.palette.chart which is undefined. We assume the array above in defaultTheme (the array of objects with keys of main) isn't being added/registered correctly.

Please let me know if there's any other info that could be of help if you have trouble reproducing it.

**Comment by ccasher** [comment]
Hi @lukebeamish-peak, thanks for submitting this issue. Could you please confirm if this issue still arises with a fresh clone/fork of backstage or a new backstage create-app?

**Comment by lukebeamish-peak** [comment]
Hi @ccasher I've just tested it out on a fresh instance of Backstage and it appears to be working correctly. We can take another look at our instance and let you know if we find anything we missed previously.

**Comment by lukebeamish-peak** [comment]
We noticed some differences between our package versions and the ones used by the fresh install, updating everything to the latest versions and forcing a fresh install seems to have fixed it. Please feel free to close off this issue. I've pasted the different frontend packages we were using below in case it's useful to anyone else.

App package.json old version:
```
"dependencies": {
    "@backstage/app-defaults": "^1.0.0",
    "@backstage/catalog-model": "^1.0.0",
    "@backstage/cli": "^0.17.0",
    "@backstage/core-app-api": "^1.0.0",
    "@backstage/core-components": "^0.9.0",
    "@backstage/core-plugin-api": "^1.0.0",
    "@backstage/integration-react": "^1.0.0",
    "@backstage/plugin-api-docs": "^0.8.1",
    "@backstage/plugin-catalog": "^1.0.0",
    "@backstage/plugin-catalog-common": "^1.0.0",
    "@backstage/plugin-catalog-graph": "^0.2.7",
    "@backstage/plugin-catalog-import": "^0.8.0",
    "@backstage/plugin-catalog-react": "^1.0.0",
    "@backstage/plugin-explore": "^0.3.7",
    "@backstage/plugin-github-actions": "^0.5.1",
    "@backstage/plugin-home": "^0.4.20",
    "@backstage/plugin-org": "^0.5.1",
    "@backstage/plugin-permission-react": "^0.4.0",
    "@backstage/plugin-scaffolder": "^1.0.0",
    "@backstage/plugin-search": "^0.8.0",
    "@backstage/plugin-shortcuts": "^0.2.4",
    "@backstage/plugin-search-react": "^0.1.0",
    "@backstage/plugin-tech-radar": "^0.5.0",
    "@backstage/plugin-techdocs": "^1.0.0",
    "@backstage/plugin-user-settings": "^0.4.0",
    "@backstage/test-utils": "^1.0.0",
    "@backstage/theme": "^0.2.8",
    "@backstage/plugin-permission-react": "^0.4.0",
    "@backstage/plugin-catalog-common": "^1.0.0",
    "@internal/plugin-aws-permission-management": "^0.1.0",
    "@internal/plugin-confluence": "^0.1.0",
    "@internal/plugin-github-search": "^0.1.0",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@roadiehq/backstage-plugin-github-insights": "^1.4.5",
    "@roadiehq/backstage-plugin-github-pull-requests": "^1.3.5",
	@@ -52,12 +54,13 @@
    "react-use": "^15.3.3"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^10.4.1",
    "@testing-library/user-event": "^12.0.7",
    "@types/jest": "^26.0.7",
    "@types/node": "^14.14.32",
    "@types/react-dom": "^16.9.8",
    "cross-env": "^7.0.0",
    "cypress": "^7.3.0",
    "eslint-plugin-cypress": "^2.10.3",
    "start-server-and-test": "^1.10.11"
  },
```

App package.json new version:
```
 "dependencies": {
    "@backstage/app-defaults": "^1.0.2",
    "@backstage/catalog-model": "^1.0.2",
    "@backstage/cli": "^0.17.1",
    "@backstage/core-app-api": "^1.0.2",
    "@backstage/core-components": "^0.9.4",
    "@backstage/core-plugin-api": "^1.0.2",
    "@backstage/integration-react": "^1.1.0",
    "@backstage/plugin-api-docs": "^0.8.5",
    "@backstage/plugin-catalog": "^1.2.0",
    "@backstage/plugin-catalog-common": "^1.0.2",
    "@backstage/plugin-catalog-graph": "^0.2.17",
    "@backstage/plugin-catalog-import": "^0.8.8",
    "@backstage/plugin-catalog-react": "^1.1.0",
    "@backstage/plugin-explore": "^0.3.7",
    "@backstage/plugin-github-actions": "^0.5.5",
    "@backstage/plugin-home": "^0.4.20",
    "@backstage/plugin-org": "^0.5.5",
    "@backstage/plugin-permission-react": "^0.4.1",
    "@backstage/plugin-scaffolder": "^1.2.0",
    "@backstage/plugin-search": "^0.8.1",
    "@backstage/plugin-search-react": "^0.2.0",
    "@backstage/plugin-shortcuts": "^0.2.4",
    "@backstage/plugin-tech-radar": "^0.5.12",
    "@backstage/plugin-techdocs": "^1.1.1",
    "@backstage/plugin-techdocs-module-addons-contrib": "^1.0.0",
    "@backstage/plugin-techdocs-react": "^1.0.0",
    "@backstage/plugin-user-settings": "^0.4.4",
    "@backstage/test-utils": "^1.0.0",
    "@backstage/theme": "^0.2.15",
    "@cloud-carbon-footprint/backstage-plugin-frontend": "^0.0.2",
    "@internal/plugin-aws-permission-management": "^0.1.0",
    "@internal/plugin-confluence": "^0.1.0",
    "@internal/plugin-github-search": "^0.1.0",
    "@material-ui-extra/icons": "^1.1.30",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.9.1",
    "@roadiehq/backstage-plugin-github-insights": "^1.4.5",
    "@roadiehq/backstage-plugin-github-pull-requests": "^1.3.5",
	@@ -52,12 +54,13 @@
    "react-use": "^15.3.3"
  },
  "devDependencies": {
    "@backstage/test-utils": "^1.1.0",
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^12.0.7",
    "@types/jest": "^26.0.7",
    "@types/node": "^14.14.32",
    "@types/react-dom": "*",
    "cross-env": "^7.0.0",
    "cypress": "^7.3.0",
    "eslint-plugin-cypress": "^2.10.3",
    "start-server-and-test": "^1.10.11"
  },
```

**Comment by ccasher** [comment]
Thanks for the updates @lukebeamish-peak, glad you were able to get this working!
