### ISSUE TITLE
Type and tsconfig errors relating to GCP

### ISSUE THREAD

**Issue by sammbetts** [cloud-carbon-footprint/ccf-backstage-plugin#72]
### Preflight Checklist

- [x ] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/CONTRIBUTING.md) for this project.
- [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Backstage Version:**
1.14.0
- **CCF Plugin Version:**
latest
- **Browser:**
chrome

### Expected Behavior

plugin to run without errors

### Actual Behavior

I am getting the following console error from gcp:

`2023-05-24T13:13:30.781Z [api] error: Unable to process footprint request.TypeError: Cannot read properties of undefined (reading 'forEach')
    at BillingExportTable.tagNamesToQueryColumns (......./node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:394:18)
    at BillingExportTable.getUsage (.......node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:314:52)
    at BillingExportTable.getEstimates (......./node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:30:38)
    at GCPAccount.getDataFromBillingExportTable (......./node_modules/@cloud-carbon-footprint/gcp/dist/application/GCPAccount.js:47:42)
    at Object.getCostAndEstimates (......./node_modules/@cloud-carbon-footprint/app/dist/App.js:52:116)
    at getCostAndEstimates (......./node_modules/@cloud-carbon-footprint/app/dist/Cache.js:22:72)
    at ......./node_modules/@cloud-carbon-footprint/app/dist/Cache.js:50:16
    at Array.map (<anonymous>)
    at getEstimatesForMissingDates (......./node_modules/@cloud-carbon-footprint/app/dist/Cache.js:49:76)
    at descriptor.value (......./node_modules/@cloud-carbon-footprint/app/dist/Cache.js:33:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FootprintApiMiddleware (......./node_modules/@cloud-carbon-footprint/api/dist/api.js:34:35) 
`

### To Reproduce

happens when running locally 

### Additional Information

I successfully got this working when first installed, I have come back to it after a few weeks and the errors have just appeared. I have not made any changes inside my gcp account, the auth credentials are correct, and there have been no changes to the project. I have had others test my branch and they get the same error. I have tried removing and reinstalling CCF plugin, node_modules and yarn.lock. I have tried re-cloning the project and then installing fresh, error still occurs. 

© 2022 Thoughtworks, Inc.

**Comment by 4upz** [comment]
Thanks for opening this issue and we appreciate the details and logs you provided! This seems to be an issue occurring with the latest version of our plugin when fetching GCP estimates. We're currently working on a fix and will share updates here

**Comment by 4upz** [comment]
@sammbetts This issue has been resolved with a subdependency patch for [@cloud-carbon-footprint/common](https://www.npmjs.com/package/@cloud-carbon-footprint/common) version v1.11.0. 

To upgrade your current backstage plugin to the right version. You can do one of the following:

- **Remove and Reinstall the Plugin Backend** 
  - `cd packages/backend`
  - `yarn remove @cloud-carbon-footprint/backstage-plugin-backend`
  - `yarn add @cloud-carbon-footprint/backstage-plugin-backend`
- **Deleting Lockfile and do Fresh Yarn Install**
  - Manually delete `yarn.lock` file at project root or use `rm yarn.lock`
  - `yarn cache clean`
  - `yarn install`
  
  Hope that helps! Feel free to let us know if you have any other issues!

**Comment by sammbetts** [comment]
The error has gone - thanks!
